version: 1
jobs:
  deploy_to_npm:
    image: node:10
    script:
      - npm i
      - npm install -g npm-install-peers
      - npm-install-peers
      - npm run build
      - npm install -g npm-cli-login
      - npm-cli-login -u $NPM_USER -p $NPM_PASSWORD -e $NPM_EMAIL
      - npm run publish-lib 

stages:
  - deploy:
      jobs:
        - deploy_to_npm:
            filters:
              only:
                - master